### ISSUE TITLE
Missing OS supports: Debian 9, Debian 10, Ubuntu 20.04

### ISSUE THREAD

**Issue by Neustradamus** [opencats/OpenCATS-Installation-Scripts#3]
Hello OpenCATS team,

I wish you a happy new year!

Can you add support of:
- Debian 9
- Debian 10
- Ubuntu 20.04

Thanks in advance.

**Comment by shantadam** [comment]
Hi Neustradamus,

Kindly requesting to please elaborate your specific requirement, as such:
- Were you facing some specific issues on Debian 9-10 and Ubuntu 20.04?
- Are you looking for a how to install guide?
- Are you looking for benchmark tests certification?

Your requirements is too broad.

Regards,
Shant Adam,
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by Neustradamus** [comment]
@shantadam: Thanks for your reply!

It is to be compatible with all current systems, users/devs have always Debian 9 and Debian 10 before Debian 11 in a few moment and Ubuntu 20.04, and I have not spoken about CentOS 8.

I see only:
- CentOS7-OpenCATS-install.sh
- Debian8-OpenCATS-Install.sh
- Ubuntu14.04-OpenCATS-Install.sh
- Ubuntu16.04-OpenCATS-Install.sh
- Ubuntu18.04-OpenCATS-Install.sh

**Comment by shantadam** [comment]
Thank you, @Neustradamus<mailto:notifications@github.com>,

Okay, now that you pointed out the Shell bash files, it’s clear that the requirement is specifically on these installation files.

For future reference, kindly to consider being specific when we request an action. Requirements need to be clear what it is exactly that we want and on what.

Thank you, again @Neustradamus<mailto:notifications@github.com> for the clarification.

Regards,
Shant Adam
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by Neustradamus** [comment]
@shantadam: Sorry for my first uncleared message.

Are you ready to update the installation scripts?
- Debian 9
- Debian 10
- Debian 11
- Ubuntu 20.04
- CentOS 8

**Comment by shantadam** [comment]
@Neustradamus,

Your ask is some the many requirements but to commit to it immediately, I cannot promise myself right now today. If you have the resources to update so to help us give a hand with a patch please go ahead and submit a PR we’ll review. Otherwise it’ll have to wait in queue.

Regards
Shant Adam
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

On Jan 11, 2021, at 9:24 PM, Neustradamus <notifications@github.com> wrote:

﻿

@shantadam<https://github.com/shantadam>: Sorry for my first uncleared message.

Are you ready to update the installation scripts?

  *   Debian 9
  *   Debian 10
  *   Debian 11
  *   Ubuntu 20.04
  *   CentOS 8

**Comment by cptr13** [comment]
@Neustradamus Yes, I haven't done any updates in quite a long time.  IF there are specific questions, please let me know and I'll try to help.  But I need to revisit and update the documentation.  Though it won't be for every release and probably only Ubuntu LTS versions from now on.  If you're using CentOS....you can install this software :p

**Comment by shantadam** [comment]
Thanks @cptr13 you're an angel for jumping-in on this need. @Neustradamus see if @cptr13 can be of help to you. Cheers to you both.

**Comment by Neustradamus** [comment]
@shantadam: Do not close before the solution...

**Comment by shantadam** [comment]
Reported unresolved Issue. Reopening.

**Comment by cptr13** [comment]
I am shifting documentation to docker.  It will be easier for consistency and ease of use over the long-run.  It's won't be distro-specific anymore.  Closing this out as there's no point in this.  If you want to create a general issue about updated documentation, you're welcome to.  I'm waiting on some docker information from devs to move forward.

**Comment by shantadam** [comment]
A bit of an abrupt move don’t you think, Stacey, without consulting the team?

Can you elaborate on your move? What do you mean by shifting documentation to docker?

Why would you close the issue if your given solution is unclear? Can I kindly suggest to reopen the issue with your elaboration. Thank you.

Regards,
Shant Adam
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

**Comment by shantadam** [comment]
@Neustradamus + @Stacey,

I just came to realization, I had completely forgot that I had the solution at my fingertips since last year on my local machine -i.e. Docker Compose configuration files.

I happen to have a more updated, more complete and robust version of the very basic Docker compose that exists in the repo which doesn’t work. I’ll be pushing the update to Github repo and keep you guys in the loop.

P.S.: Would you agree that our effort should be towards microservices support, less updating system specific Shell scripts and more updating Docker Compose files? Docker resolves the uniformity of installation across various systems. But, requires Docker installed.

Regards,
Shant Adam
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.


From: Shant Adam <shant.adam@mxcgi.com>
Date: Thursday, February 4, 2021 at 3:18 PM
To: opencats/OpenCATS-Installation-Scripts <reply@reply.github.com>, opencats/OpenCATS-Installation-Scripts <OpenCATS-Installation-Scripts@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: Re: [opencats/OpenCATS-Installation-Scripts] Missing OS supports: Debian 9, Debian 10, Ubuntu 20.04 (#3)
A bit of an abrupt move don’t you think, Stacey, without consulting the team?

Can you elaborate on your move? What do you mean by shifting documentation to docker?

Why would you close the issue if your given solution is unclear? Can I kindly suggest to reopen the issue with your elaboration. Thank you.

Regards,
Shant Adam
--
DISCLAIMER - This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.
